apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/namespace.yaml
  - ../../base/service-account.yaml
  - ../../base/configmap.yaml
  - ../../base/secret-provider-class.yaml
  - ../../base/deployment.yaml
  - ../../base/service.yaml
  - ../../base/hpa.yaml
  - ../../base/pdb.yaml
  - ../../base/service-monitor.yaml
  - ../../base/pod-monitor.yaml
  - ../../base/ingress.yaml

namespace: payments

commonLabels:
  environment: prod

configMapGenerator:
  - name: payments-api-config
    behavior: merge
    literals:
      - spring.profiles.active=prod

patches:
  - target:
      kind: Deployment
      name: payments-api
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 500m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 768Mi
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 2000m
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 2Gi
