spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}

mercadopago:
  access-token: ${MP_ACCESS_TOKEN_PROD}
  public-key: ${MP_PUBLIC_KEY_PROD}
  notification-url: ${MP_NOTIFICATION_URL_PROD}
