spring:
  application:
    name: payment
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

payment-order:
  expiration-minutes: 60

mercadopago:
  base-url: https://api.mercadopago.com
  connect-timeout-millis: 3000
  read-timeout-millis: 5000
