apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: payments-api-secrets-provider
  namespace: payments
  labels:
    app: payments-api
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: ${AZURE_WORKLOAD_IDENTITY_CLIENT_ID}
    keyvaultName: ${KEY_VAULT_NAME}
    objects: |
      array:
        - |
          objectName: postgresql-connection-string
          objectType: secret
          objectAlias: SPRING_DATASOURCE_URL
        - |
          objectName: postgresql-username
          objectType: secret
          objectAlias: SPRING_DATASOURCE_USERNAME
        - |
          objectName: postgresql-password
          objectType: secret
          objectAlias: SPRING_DATASOURCE_PASSWORD
        - |
          objectName: mp-access-token
          objectType: secret
          objectAlias: MP_ACCESS_TOKEN
        - |
          objectName: mp-public-key
          objectType: secret
          objectAlias: MP_PUBLIC_KEY
        - |
          objectName: mp-notification-url
          objectType: secret
          objectAlias: MP_NOTIFICATION_URL
        - |
          objectName: mp-callback-url
          objectType: secret
          objectAlias: MP_CALLBACK_URL
        - |
          objectName: application-insights-connection-string
          objectType: secret
          objectAlias: APPLICATIONINSIGHTS_CONNECTION_STRING
  secretObjects:
    - secretName: payments-api-secrets
      type: Opaque
      data:
        - key: spring.datasource.url
          objectName: SPRING_DATASOURCE_URL
        - key: spring.datasource.username
          objectName: SPRING_DATASOURCE_USERNAME
        - key: spring.datasource.password
          objectName: SPRING_DATASOURCE_PASSWORD
        - key: mercadopago.access-token
          objectName: MP_ACCESS_TOKEN
        - key: mercadopago.public-key
          objectName: MP_PUBLIC_KEY
        - key: mercadopago.notification-url
          objectName: MP_NOTIFICATION_URL
        - key: mercadopago.callback-url
          objectName: MP_CALLBACK_URL
    - secretName: observability-secrets
      type: Opaque
      data:
        - key: application-insights-connection-string
          objectName: APPLICATIONINSIGHTS_CONNECTION_STRING
