apiVersion: v1
kind: ServiceAccount
metadata:
  name: payments-api-sa
  namespace: payments
  labels:
    app: payments-api
    app.kubernetes.io/part-of: techcup
  annotations:
    azure.workload.identity/client-id: "12adbab3-182b-4f19-b2f8-eb05acdc94ce"
