apiVersion: v1
kind: ServiceAccount
metadata:
  name: payments-api-sa
  namespace: payments
  labels:
    app: payments-api
    app.kubernetes.io/part-of: techcup
  annotations:
    azure.workload.identity/client-id: ${AZURE_WORKLOAD_IDENTITY_CLIENT_ID}
